version: '3.4'

services:
  sqlinjection:
    image: sqlinjection:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SqlInjection"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sqlinjection$
    volumes:
      - /Users/tongbo/Downloads/CShape/tmp/ASP.NET-Demo/SqlInjection:/app
      - /Users/tongbo/Downloads/CShape/tmp/ASP.NET-Demo:/src
      - /Users/tongbo/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_sqlinjection$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sqlinjection$ \"bin/Debug/netcoreapp2.2/SqlInjection.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true